// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Ciz5kEQeNcoSp4AazKsy9gW9HYpVXW4',
    appId: '1:762749305196:web:2fc9bdd1d70b3ef5773349',
    messagingSenderId: '762749305196',
    projectId: 'cinnamon-marketplace-24f7d',
    authDomain: 'cinnamon-marketplace-24f7d.firebaseapp.com',
    storageBucket: 'cinnamon-marketplace-24f7d.firebasestorage.app',
    measurementId: 'G-NNP9N5ML7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9q0ahziTXXQm0UXeA_AawfrfZPY6bqc8',
    appId: '1:762749305196:android:e544d537eacff681773349',
    messagingSenderId: '762749305196',
    projectId: 'cinnamon-marketplace-24f7d',
    storageBucket: 'cinnamon-marketplace-24f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMlG7qAaHw_VDar8hq4P6SsEPqVkUAVY',
    appId: '1:762749305196:ios:56ea44af88c75667773349',
    messagingSenderId: '762749305196',
    projectId: 'cinnamon-marketplace-24f7d',
    storageBucket: 'cinnamon-marketplace-24f7d.firebasestorage.app',
    iosBundleId: 'com.example.cinnamonmarketplace',
  );
}
